// frameworks/non-keyed/react-mobX/src/Main.jsx
"use strict";

var React = require("react");
var ReactDOM = require("react-dom");
require("mobx-react/batchingForReactDom");
const { Row } = require("./Row");
var { observer } = require("mobx-react");
var { observable, computed } = require("mobx");
const { Store } = require("./Store");

@observer
export class Main extends React.Component {
  constructor(props) {
    super(props);
    this.select = this.select.bind(this);
    this.delete = this.delete.bind(this);
    this.add = this.add.bind(this);
    this.run = this.run.bind(this);
    this.update = this.update.bind(this);
    this.runLots = this.runLots.bind(this);
    this.clear = this.clear.bind(this);
    this.swapRows = this.swapRows.bind(this);
    this.start = 0;
  }
  run() {
    this.props.store.run();
  }
  add() {
    this.props.store.add();
  }
  update() {
    this.props.store.update();
  }
  select(row) {
    this.props.store.select(row);
  }
  delete(row) {
    this.props.store.delete(row);
  }
  runLots() {
    this.props.store.runLots();
  }
  clear() {
    this.props.store.clear();
  }
  swapRows() {
    this.props.store.swapRows();
  }
  render() {
    return (
      <div className="container">
        <div className="jumbotron">
          <div className="row">
            <div className="col-md-6">
              <h1>React + Mobx (non-keyed)</h1>
            </div>
            <div className="col-md-6">
              <div className="row">
                <div className="col-sm-6 smallpad">
                  <button
                    type="button"
                    className="btn btn-primary btn-block"
                    id="run"
                    onClick={this.run}
                  >
                    Create 1,000 rows
                  </button>
                </div>
                <div className="col-sm-6 smallpad">
                  <button
                    type="button"
                    className="btn btn-primary btn-block"
                    id="runlots"
                    onClick={this.runLots}
                  >
                    Create 10,000 rows
                  </button>
                </div>
                <div className="col-sm-6 smallpad">
                  <button
                    type="button"
                    className="btn btn-primary btn-block"
                    id="add"
                    onClick={this.add}
                  >
                    Append 1,000 rows
                  </button>
                </div>
                <div className="col-sm-6 smallpad">
                  <button
                    type="button"
                    className="btn btn-primary btn-block"
                    id="update"
                    onClick={this.update}
                  >
                    Update every 10th row
                  </button>
                </div>
                <div className="col-sm-6 smallpad">
                  <button
                    type="button"
                    className="btn btn-primary btn-block"
                    id="clear"
                    onClick={this.clear}
                  >
                    Clear
                  </button>
                </div>
                <div className="col-sm-6 smallpad">
                  <button
                    type="button"
                    className="btn btn-primary btn-block"
                    id="swaprows"
                    onClick={this.swapRows}
                  >
                    Swap Rows
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <table className="table table-hover table-striped test-data">
          <tbody>
            {this.props.store.data.map((d, i) => {
              return (
                <Row
                  key={i}
                  data={d}
                  onClick={this.select}
                  onDelete={this.delete}
                ></Row>
              );
            })}
          </tbody>
        </table>
        <span
          className="preloadicon glyphicon glyphicon-remove"
          aria-hidden="true"
        ></span>
      </div>
    );
  }
}

let store = new Store();

ReactDOM.render(<Main store={store} />, document.getElementById("main"));

// frameworks/keyed/lit-element/src/main.ts
import { LitElement, html, customElement, property } from 'lit-element';
import { repeat } from 'lit-html/directives/repeat';
import { Store } from './store';

const store = new Store();

@customElement('main-element')
export class MainElement extends LitElement {
    @property()
    _rows = store.data;

    @property()
    _selected = store.selected;

    render() {
        return html`
        <link href="/css/currentStyle.css" rel="stylesheet"/>
        <div class="container">
            <div class="jumbotron">
                <div class="row">
                    <div class="col-md-6">
                        <h1>lit-element 2.2.1 keyed</h1>
                    </div>
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-sm-6 smallpad">
                            <button type="button" class="btn btn-primary btn-block" id="run" @click=${this._run}>Create 1,000 rows</button>
                            </div>
                            <div class="col-sm-6 smallpad">
                                <button type="button" class="btn btn-primary btn-block" id="runlots" @click=${this._runLots}>Create 10,000 rows</button>
                            </div>
                            <div class="col-sm-6 smallpad">
                                <button type="button" class="btn btn-primary btn-block" id="add" @click=${this._add}>Append 1,000 rows</button>
                            </div>
                            <div class="col-sm-6 smallpad">
                                <button type="button" class="btn btn-primary btn-block" id="update" @click=${this._update}>Update every 10th row</button>
                            </div>
                            <div class="col-sm-6 smallpad">
                                <button type="button" class="btn btn-primary btn-block" id="clear" @click=${this._clear}>Clear</button>
                            </div>
                            <div class="col-sm-6 smallpad">
                                <button type="button" class="btn btn-primary btn-block" id="swaprows" @click=${this._swapRows}>Swap Rows</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-hover table-striped test-data" @click=${this._handleClick}>
                <tbody>${repeat(this._rows, item => item.id, item => html`
                <tr id=${item.id} class=${item.id == this._selected ? 'danger' : ''}>
                    <td class="col-md-1">${item.id}</td>
                    <td class="col-md-4">
                    <a data-action="select" data-id=${item.id}>${item.label}</a>
                    </td>
                    <td class="col-md-1">
                    <a>
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"
                            data-action="remove" data-id=${item.id}></span>
                    </a>
                    </td>
                    <td class="col-md-6"></td>
                </tr>`)}
                </tbody>
            </table>
            <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true"></span>
        </div>
        `;
    }

    _handleClick(e) {
        const { action, id } = e.target.dataset
        if (action && id) {
            this['_' + action](id)
        }
    }
    _add() {
        store.add();
        this._sync();
    }
    _remove(id) {
        store.delete(id);
        this._sync();
    }
    _select(id) {
        store.select(id);
        this._sync();
    }
    _run() {
        store.run();
        this._sync();
    }
    _update() {
        store.update();
        this._sync();
    }
    _runLots() {
        store.runLots();
        this._sync();
    }
    _clear() {
        store.clear();
        this._sync();
    }
    _swapRows() {
        store.swapRows();
        this._sync();
    }
    _sync() {
        this._rows = store.data;
        this._selected = store.selected;
    }
}
